from odoo import models, fields, api


class SpoilageIncident(models.Model):
    _name = 'spoilage.incident'
    _description = 'Cold-Chain Spoilage Incident & Investigation'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'detected_date desc'

    name = fields.Char(
        string="Incident Reference",
        required=True,
        copy=False,
        readonly=True,
        default='New'
    )

    lot_id = fields.Many2one(
        'stock.lot',
        string="Affected Lot / Serial",
        required=True,
        tracking=True
    )

    picking_id = fields.Many2one(
        'stock.picking',
        string="Related Transfer",
        tracking=True
    )

    detected_date = fields.Datetime(
        string="Detected Date",
        default=fields.Datetime.now,
        required=True
    )

    peak_breached_temp = fields.Float(
        string="Peak Breached Temp (°C)",
        tracking=True
    )

    excursion_duration_hours = fields.Float(
        string="Excursion Duration (Hours)"
    )

    severity_level = fields.Selection([
        ('minor', 'Minor (Slight Shelf-Life Impact)'),
        ('moderate', 'Moderate (Requires Markdown / Reroute)'),
        ('critical', 'Critical (Complete Loss / Scrap Required)')
    ], string="Severity Level", default='minor', tracking=True)

    ai_action_recommendation = fields.Text(
        string="AI Remediation Recommendation",
        help="Dynamic action plan generated by LLM / degradation engine."
    )

    investigation_state = fields.Selection([
        ('logged', 'Logged'),
        ('qa_review', 'QA Review'),
        ('cleared', 'Cleared'),
        ('discounted', 'Discounted & Liquidated'),
        ('scrapped', 'Scrapped')
    ], string="Investigation State", default='logged', tracking=True)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                vals['name'] = (
                    self.env['ir.sequence'].next_by_code('spoilage.incident')
                    or 'INC-00001'
                )

        return super().create(vals_list)

    def action_approve_qa(self):
        self.write({'investigation_state': 'qa_review'})

    def action_clear(self):
        self.write({'investigation_state': 'cleared'})
        if self.lot_id:
            self.lot_id.write({'batch_health': 'optimal'})

    def action_discount(self):
        self.write({'investigation_state': 'discounted'})
        if self.lot_id:
            self.lot_id.write({'batch_health': 'warning'})

    def action_scrap(self):
        self.write({'investigation_state': 'scrapped'})
        if self.lot_id:
            self.lot_id.write({'batch_health': 'compromised'})